CREATE TABLESPACE trn_act1 DATAFILE '/opt/oracle/oradata/XE/trn_art1_01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;
CREATE TABLESPACE idx_act1 DATAFILE '/opt/oracle/oradata/XE/idx_art1_01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE USER act1 IDENTIFIED BY act1_01 DEFAULT TABLESPACE trn_act1;