SELECT
date1.YEAR ,
ma.ACCOUNT_TYPE , ma.ACCOUNT_CODE, ma.ACCOUNT_NAME ,
sum( COALESCE(tj2.DEBIT_AMOUNT, 0) + coalesce( tj2.CREDIT_AMOUNT,0) * -1 ) AS AMOUNT
FROM T_JOURNAL_HEADER tj1
INNER JOIN (
SELECT
'2025' AS YEAR,
to_date('2025-04-01','YYYY-MM-DD') AS FROMDATE,
add_months(to_date('2025-04-01','YYYY-MM-DD'),12) AS TODATE
FROM dual
UNION
SELECT
'2026' AS YEAR,
to_date('2026-04-01','YYYY-MM-DD') AS FROMDATE,
add_months(to_date('2026-04-01','YYYY-MM-DD'),12) AS TODATE
FROM dual
) date1 ON tj1.JOURNAL_DATE >= date1.FROMDATE
AND tj1.JOURNAL_DATE < date1.TODATE
INNER JOIN T_JOURNAL_DETAIL tj2 ON tj1.JOURNAL_ID = tj2.JOURNAL_ID
INNER JOIN M_ACCOUNT ma ON tj2.account_ID = ma.ACCOUNT_ID
GROUP BY
date1.YEAR ,
ma.ACCOUNT_TYPE , ma.ACCOUNT_CODE, ma.ACCOUNT_NAME
ORDER BY date1.YEAR, ma.ACCOUNT_CODE
