SELECT
date1.YEAR ,
mc.COMPANY_CODE , mc.COMPANY_NAME ,
ma.ACCOUNT_TYPE , ma.ACCOUNT_CODE, ma.ACCOUNT_NAME ,
sum( COALESCE(tj2.DEBIT_AMOUNT, 0) + coalesce( tj2.CREDIT_AMOUNT,0) * -1 ) AS AMOUNT
FROM T_JOURNAL_HEADER tj1
INNER JOIN (
SELECT
'2026' AS YEAR,
to_date('2026-04-01','YYYY-MM-DD') AS FROMDATE,
add_months(to_date('2026-04-01','YYYY-MM-DD'),12) AS TODATE
FROM dual
) date1 ON tj1.JOURNAL_DATE >= date1.FROMDATE
AND tj1.JOURNAL_DATE < date1.TODATE
INNER JOIN T_JOURNAL_DETAIL tj2 ON tj1.JOURNAL_ID = tj2.JOURNAL_ID
INNER JOIN act1.M_COMPANY mc ON tj1.COMPANY_ID = mc.COMPANY_ID
INNER JOIN M_ACCOUNT ma ON tj2.account_ID = ma.ACCOUNT_ID
WHERE tj1.COMPANY_ID = 10
GROUP BY
date1.YEAR ,
mc.COMPANY_CODE , mc.COMPANY_NAME ,
ma.ACCOUNT_TYPE , ma.ACCOUNT_CODE, ma.ACCOUNT_NAME
ORDER BY date1.YEAR, mc.COMPANY_CODE,ma.ACCOUNT_CODE
