SELECT
to_char(tj1.JOURNAL_DATE,'yyyymm') AS MONTH,
ma.ACCOUNT_TYPE , ma.ACCOUNT_CODE, ma.ACCOUNT_NAME ,
sum( coalesce(tj2.DEBIT_AMOUNT, 0) + coalesce(tj2.CREDIT_AMOUNT,0) * -1 ) AS AMOUNT
FROM act1.T_JOURNAL_HEADER tj1
INNER JOIN act1.T_JOURNAL_DETAIL tj2 ON tj1.JOURNAL_ID = tj2.JOURNAL_ID
INNER JOIN act1.M_ACCOUNT ma ON tj2.account_ID = ma.ACCOUNT_ID
WHERE tj1.JOURNAL_DATE >= '2026-01-01'
AND tj1.JOURNAL_DATE <= '2026-01-31'
and tj2.account_id = 1
GROUP BY
to_char(tj1.JOURNAL_DATE,'yyyymm'),
ma.ACCOUNT_TYPE , ma.ACCOUNT_CODE, ma.ACCOUNT_NAME
ORDER BY ma.ACCOUNT_CODE, to_char(tj1.JOURNAL_DATE,'yyyymm');
