SELECT
date_trunc('MONTH',tj1.JOURNAL_DATE) AS MONTH,
ma.ACCOUNT_TYPE , ma.ACCOUNT_CODE, ma.ACCOUNT_NAME ,
sum( coalesce(tj2.DEBIT_AMOUNT, 0) + coalesce(tj2.CREDIT_AMOUNT,0) * -1 ) AS AMOUNT
FROM act1.T_JOURNAL_HEADER tj1
JOIN act1.T_JOURNAL_DETAIL tj2 ON tj1.JOURNAL_ID = tj2.JOURNAL_ID
JOIN act1.M_ACCOUNT ma ON tj2.account_ID = ma.ACCOUNT_ID
WHERE tj1.JOURNAL_DATE >= '2026-01-01'
AND tj1.JOURNAL_DATE < '2026-02-01'
and tj2.account_id = 1
GROUP BY
date_trunc('MONTH',tj1.JOURNAL_DATE),
ma.ACCOUNT_TYPE , ma.ACCOUNT_CODE, ma.ACCOUNT_NAME
ORDER BY 2,1;
