SELECT
m1.COMPANY_CODE , m1.COMPANY_NAME ,
m2.PARTY_CODE , m2.PARTY_NAME ,
tj1.JOURNAL_DATE,
tj1.JOURNAL_ID ,
tj1.DESCRIPTION,
tj2.LINE_NO ,
m3.ACCOUNT_TYPE, m3.ACCOUNT_CODE, m3.ACCOUNT_NAME,
COALESCE(tj2.DEBIT_AMOUNT,0) + COALESCE(tj2.CREDIT_AMOUNT,0) * -1 AMOUNT
FROM act1.t_journal_header tj1
inner JOIN act1.t_journal_detail tj2 ON tj1.JOURNAL_ID = tj2.JOURNAL_ID
inner JOIN act1.m_company m1 ON tj1.COMPANY_ID = m1.COMPANY_ID
inner JOIN act1.m_party m2 ON tj1.PARTY_ID = m2.PARTY_ID
inner JOIN act1.m_account m3 ON tj2.ACCOUNT_ID = m3.ACCOUNT_ID
WHERE tj1.JOURNAL_ID = 5618
AND tj2.ACCOUNT_ID = 1
ORDER BY
tj1.COMPANY_ID ,
tj1.PARTY_ID ,
tj1.JOURNAL_DATE,
tj1.JOURNAL_ID ,
tj2.LINE_NO ;
