version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: poc-postgres
    restart: always
    environment:
      POSTGRES_USER: poc_user
      POSTGRES_PASSWORD: poc_pass
      POSTGRES_DB: poc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_buffers=512MB
      -c work_mem=16MB
      -c logging_collector=on
      -c log_statement=all

  pgadmin:
    image: dpage/pgadmin4
    container_name: poc-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data: