DROP TABLE act1.m_party CASCADE;

CREATE TABLE act1.m_party(
    party_id NUMERIC NOT NULL,
    party_code CHARACTER VARYING(20) NOT NULL,
    party_name CHARACTER VARYING(100) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT (CLOCK_TIMESTAMP() AT TIME ZONE COALESCE(CURRENT_SETTING('aws_oracle_ext.tz', TRUE), 'UTC'))::TIMESTAMP(0)
)
        WITH (
        OIDS=FALSE
        );

ALTER TABLE act1.m_party ADD PRIMARY KEY (party_id);