SELECT
to_char(tj1.JOURNAL_DATE,'yyyymm') AS MONTH,
mc.COMPANY_CODE , mc.COMPANY_NAME ,
ma.ACCOUNT_TYPE , ma.ACCOUNT_CODE, ma.ACCOUNT_NAME ,
sum( coalesce(tj2.DEBIT_AMOUNT, 0) + coalesce(tj2.CREDIT_AMOUNT,0) * -1 ) AS AMOUNT
FROM act1.T_JOURNAL_HEADER tj1
INNER JOIN act1.T_JOURNAL_DETAIL tj2 ON tj1.JOURNAL_ID = tj2.JOURNAL_ID
INNER JOIN act1.M_COMPANY mc ON tj1.COMPANY_ID = mc.COMPANY_ID
INNER JOIN act1.M_ACCOUNT ma ON tj2.account_ID = ma.ACCOUNT_ID
where tj1.company_id = 3
GROUP BY
to_char(tj1.JOURNAL_DATE,'yyyymm'),
mc.COMPANY_CODE , mc.COMPANY_NAME ,
ma.ACCOUNT_TYPE , ma.ACCOUNT_CODE, ma.ACCOUNT_NAME
ORDER BY to_char(tj1.JOURNAL_DATE,'yyyymm'), mc.COMPANY_CODE, ma.ACCOUNT_CODE;
