SELECT
t1.COMPANY_CODE , t1.COMPANY_NAME ,
t1.PARTY_CODE , t1.PARTY_NAME ,
t1.JOURNAL_DATE ,
t1.JOURNAL_ID ,
t1.DESCRIPTION ,
t1.LINE_NO ,
t1.ACCOUNT_TYPE , t1.ACCOUNT_CODE , t1.ACCOUNT_NAME ,
t1.DRCR_AMOUNT
FROM act1.t_journal_9999A00 t1
WHERE t1.COMPANY_ID = 2
ORDER BY
t1.COMPANY_ID ,
t1.PARTY_ID ,
t1.JOURNAL_DATE,
t1.JOURNAL_ID ,
t1.LINE_NO ;
